INSERT INTO PRODUTO(DESCRICAO, VALOR) values('ARROZ', 20.00), ('TOMATE', 4.0), ('LEITE', 5.0);

INSERT INTO VENDA(DATA) values (CURRENT_TIMESTAMP);
INSERT INTO VENDA(DATA) values (CURRENT_TIMESTAMP);
INSERT INTO VENDA(DATA) values (CURRENT_TIMESTAMP);

INSERT INTO ITEM_VENDA(QUANTIDADE, PRODUTO_ID, VENDA_ID) values (2.0, 2, 1);
INSERT INTO ITEM_VENDA(QUANTIDADE, PRODUTO_ID, VENDA_ID) values (4.0, 1, 2);
INSERT INTO ITEM_VENDA(QUANTIDADE, PRODUTO_ID, VENDA_ID) values (1.0, 3, 3);

